# html lang
language: en

# main menu navigation
menu:
  Home:
    icon: home
    title: 首页
    href: /
  Archives:
    icon: list-ul
    title: 归档
    href: /archives
  Tags:
    icon: tags
    title: 标签
    href: /tags
  Github:
    icon: github
    title: Github
    href: http://www.github.com/

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/minion.css
- //fonts.useso.com/css?family=Roboto
- //fonts.useso.com/css?family=Source+Code+Pro
# - //fonts.googleapis.com/css?family=Roboto
# - //fonts.googleapis.com/css?family=Source+Code+Pro
- //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

# scripts loaded in the end of the body
scripts:
- //cdn.bootcss.com/jquery/2.0.3/jquery.min.js
- /js/nprogress.js
- /js/minion.js

# ICP备案号 如果有备案 请取消注释 并如实填写
# icp: 京ICP备12345678